language: php
dist: trusty
php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2
- 7.3

before_script:
- composer config -g github-oauth.github.com 7cecf3a16747d8cc66e21b459aaa233356e95dde
- composer global require "fxp/composer-asset-plugin:^1.3.1"
- composer install

script:
- vendor/bin/phpunit ./tests/
